version: '3.8'
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    command: npm run start:dev
    environment:
      DATABASE_HOST: db # to allow run app locally w/o docker.
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - db  
    volumes:
      - .:/usr/src/app
  db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 5